[2025-06-11T17:42:36.443+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-11T15:27:00.244031+00:00 [queued]>
[2025-06-11T17:42:36.491+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-11T15:27:00.244031+00:00 [queued]>
[2025-06-11T17:42:36.491+0200] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-06-11T17:42:36.491+0200] {taskinstance.py:1280} INFO - Starting attempt 4 of 4
[2025-06-11T17:42:36.491+0200] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-06-11T17:42:36.521+0200] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): pyspark_train_classifier_model> on 2025-06-11 15:27:00.244031+00:00
[2025-06-11T17:42:36.523+0200] {standard_task_runner.py:55} INFO - Started process 174741 to run task
[2025-06-11T17:42:36.530+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'agile_data_science_batch_prediction_model_training', 'pyspark_train_classifier_model', 'manual__2025-06-11T15:27:00.244031+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmpjxt5xa0n']
[2025-06-11T17:42:36.532+0200] {standard_task_runner.py:83} INFO - Job 11: Subtask pyspark_train_classifier_model
[2025-06-11T17:42:36.662+0200] {task_command.py:388} INFO - Running <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-11T15:27:00.244031+00:00 [running]> on host l090.lab.dit.upm.es
[2025-06-11T17:42:36.829+0200] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=agile_data_science_batch_prediction_model_training
AIRFLOW_CTX_TASK_ID=pyspark_train_classifier_model
AIRFLOW_CTX_EXECUTION_DATE=2025-06-11T15:27:00.244031+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-06-11T15:27:00.244031+00:00
[2025-06-11T17:42:36.830+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-11T17:42:36.831+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\nspark-submit --master local[4]   /home/monica.fernandez/practica_creativa//resources/train_spark_mllib_model.py   /home/monica.fernandez/practica_creativa/']
[2025-06-11T17:42:36.838+0200] {subprocess.py:86} INFO - Output:
[2025-06-11T17:42:39.640+0200] {subprocess.py:93} INFO - 25/06/11 17:42:39 WARN Utils: Your hostname, l090 resolves to a loopback address: 127.0.1.1; using 138.4.31.90 instead (on interface enp3s0)
[2025-06-11T17:42:39.649+0200] {subprocess.py:93} INFO - 25/06/11 17:42:39 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2025-06-11T17:42:40.677+0200] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-06-11T17:42:40.678+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/resources/train_spark_mllib_model.py", line 6, in <module>
[2025-06-11T17:42:40.678+0200] {subprocess.py:93} INFO -     import mlflow
[2025-06-11T17:42:40.678+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/mlflow/__init__.py", line 44, in <module>
[2025-06-11T17:42:40.679+0200] {subprocess.py:93} INFO -     from mlflow import (
[2025-06-11T17:42:40.679+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/mlflow/artifacts/__init__.py", line 11, in <module>
[2025-06-11T17:42:40.679+0200] {subprocess.py:93} INFO -     from mlflow.entities.file_info import FileInfo
[2025-06-11T17:42:40.679+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/mlflow/entities/__init__.py", line 6, in <module>
[2025-06-11T17:42:40.680+0200] {subprocess.py:93} INFO -     from mlflow.entities.assessment import (
[2025-06-11T17:42:40.680+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/mlflow/entities/assessment.py", line 12, in <module>
[2025-06-11T17:42:40.681+0200] {subprocess.py:93} INFO -     from mlflow.entities.assessment_error import AssessmentError
[2025-06-11T17:42:40.681+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/mlflow/entities/assessment_error.py", line 6, in <module>
[2025-06-11T17:42:40.681+0200] {subprocess.py:93} INFO -     from mlflow.utils.annotations import experimental
[2025-06-11T17:42:40.681+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/mlflow/utils/__init__.py", line 10, in <module>
[2025-06-11T17:42:40.682+0200] {subprocess.py:93} INFO -     from mlflow.utils.pydantic_utils import IS_PYDANTIC_V2_OR_NEWER  # noqa: F401
[2025-06-11T17:42:40.690+0200] {subprocess.py:93} INFO -     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-06-11T17:42:40.690+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/mlflow/utils/pydantic_utils.py", line 3, in <module>
[2025-06-11T17:42:40.690+0200] {subprocess.py:93} INFO -     import pydantic
[2025-06-11T17:42:40.690+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/pydantic/__init__.py", line 5, in <module>
[2025-06-11T17:42:40.691+0200] {subprocess.py:93} INFO -     from ._migration import getattr_migration
[2025-06-11T17:42:40.691+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/pydantic/_migration.py", line 4, in <module>
[2025-06-11T17:42:40.692+0200] {subprocess.py:93} INFO -     from .version import version_short
[2025-06-11T17:42:40.692+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/pydantic/version.py", line 5, in <module>
[2025-06-11T17:42:40.693+0200] {subprocess.py:93} INFO -     from pydantic_core import __version__ as __pydantic_core_version__
[2025-06-11T17:42:40.693+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/pydantic_core/__init__.py", line 30, in <module>
[2025-06-11T17:42:40.694+0200] {subprocess.py:93} INFO -     from .core_schema import CoreConfig, CoreSchema, CoreSchemaType, ErrorType
[2025-06-11T17:42:40.694+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/pydantic_core/core_schema.py", line 16, in <module>
[2025-06-11T17:42:40.696+0200] {subprocess.py:93} INFO -     from typing_extensions import deprecated
[2025-06-11T17:42:40.696+0200] {subprocess.py:93} INFO - ImportError: cannot import name 'deprecated' from 'typing_extensions' (/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/typing_extensions.py)
[2025-06-11T17:42:40.773+0200] {subprocess.py:93} INFO - 25/06/11 17:42:40 INFO ShutdownHookManager: Shutdown hook called
[2025-06-11T17:42:40.774+0200] {subprocess.py:93} INFO - 25/06/11 17:42:40 INFO ShutdownHookManager: Deleting directory /tmp/spark-142e9ba2-698d-4adf-85bf-034d651001e8
[2025-06-11T17:42:40.882+0200] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-11T17:42:40.898+0200] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-11T17:42:40.905+0200] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=agile_data_science_batch_prediction_model_training, task_id=pyspark_train_classifier_model, execution_date=20250611T152700, start_date=20250611T154236, end_date=20250611T154240
[2025-06-11T17:42:40.963+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 11 for task pyspark_train_classifier_model (Bash command failed. The command returned a non-zero exit code 1.; 174741)
[2025-06-11T17:42:40.973+0200] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-06-11T17:42:41.023+0200] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
