[2025-06-11T17:32:16.619+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-11T15:27:00.244031+00:00 [queued]>
[2025-06-11T17:32:16.650+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-11T15:27:00.244031+00:00 [queued]>
[2025-06-11T17:32:16.650+0200] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-06-11T17:32:16.651+0200] {taskinstance.py:1280} INFO - Starting attempt 2 of 4
[2025-06-11T17:32:16.651+0200] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-06-11T17:32:16.675+0200] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): pyspark_train_classifier_model> on 2025-06-11 15:27:00.244031+00:00
[2025-06-11T17:32:16.679+0200] {standard_task_runner.py:55} INFO - Started process 169008 to run task
[2025-06-11T17:32:16.683+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'agile_data_science_batch_prediction_model_training', 'pyspark_train_classifier_model', 'manual__2025-06-11T15:27:00.244031+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmpslnhhdpf']
[2025-06-11T17:32:16.685+0200] {standard_task_runner.py:83} INFO - Job 4: Subtask pyspark_train_classifier_model
[2025-06-11T17:32:16.823+0200] {task_command.py:388} INFO - Running <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-11T15:27:00.244031+00:00 [running]> on host l090.lab.dit.upm.es
[2025-06-11T17:32:16.967+0200] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=agile_data_science_batch_prediction_model_training
AIRFLOW_CTX_TASK_ID=pyspark_train_classifier_model
AIRFLOW_CTX_EXECUTION_DATE=2025-06-11T15:27:00.244031+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-06-11T15:27:00.244031+00:00
[2025-06-11T17:32:16.974+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-11T17:32:16.975+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\nspark-submit --master SPARK_MASTER_URL=spark://spark-master:7077   /home/monica.fernandez/practica_creativa//resources/train_spark_mllib_model.py   /home/monica.fernandez/practica_creativa/']
[2025-06-11T17:32:16.995+0200] {subprocess.py:86} INFO - Output:
[2025-06-11T17:32:19.695+0200] {subprocess.py:93} INFO - 25/06/11 17:32:19 WARN Utils: Your hostname, l090 resolves to a loopback address: 127.0.1.1; using 138.4.31.90 instead (on interface enp3s0)
[2025-06-11T17:32:19.699+0200] {subprocess.py:93} INFO - 25/06/11 17:32:19 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2025-06-11T17:32:19.859+0200] {subprocess.py:93} INFO - Exception in thread "main" org.apache.spark.SparkException: Master must either be yarn or start with spark, mesos, k8s, or local
[2025-06-11T17:32:19.859+0200] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.error(SparkSubmit.scala:1047)
[2025-06-11T17:32:19.860+0200] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:256)
[2025-06-11T17:32:19.860+0200] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:964)
[2025-06-11T17:32:19.860+0200] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
[2025-06-11T17:32:19.860+0200] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
[2025-06-11T17:32:19.860+0200] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2025-06-11T17:32:19.860+0200] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2025-06-11T17:32:19.860+0200] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2025-06-11T17:32:19.861+0200] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-06-11T17:32:19.910+0200] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-11T17:32:19.930+0200] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-11T17:32:19.934+0200] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=agile_data_science_batch_prediction_model_training, task_id=pyspark_train_classifier_model, execution_date=20250611T152700, start_date=20250611T153216, end_date=20250611T153219
[2025-06-11T17:32:19.955+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 4 for task pyspark_train_classifier_model (Bash command failed. The command returned a non-zero exit code 1.; 169008)
[2025-06-11T17:32:19.995+0200] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-06-11T17:32:20.067+0200] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
