[2025-06-11T17:37:25.096+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-11T15:27:00.244031+00:00 [queued]>
[2025-06-11T17:37:25.132+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-11T15:27:00.244031+00:00 [queued]>
[2025-06-11T17:37:25.132+0200] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-06-11T17:37:25.132+0200] {taskinstance.py:1280} INFO - Starting attempt 3 of 4
[2025-06-11T17:37:25.132+0200] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-06-11T17:37:25.153+0200] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): pyspark_train_classifier_model> on 2025-06-11 15:27:00.244031+00:00
[2025-06-11T17:37:25.155+0200] {standard_task_runner.py:55} INFO - Started process 171874 to run task
[2025-06-11T17:37:25.164+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'agile_data_science_batch_prediction_model_training', 'pyspark_train_classifier_model', 'manual__2025-06-11T15:27:00.244031+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmpb6n64q31']
[2025-06-11T17:37:25.166+0200] {standard_task_runner.py:83} INFO - Job 7: Subtask pyspark_train_classifier_model
[2025-06-11T17:37:25.284+0200] {task_command.py:388} INFO - Running <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-11T15:27:00.244031+00:00 [running]> on host l090.lab.dit.upm.es
[2025-06-11T17:37:25.378+0200] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=agile_data_science_batch_prediction_model_training
AIRFLOW_CTX_TASK_ID=pyspark_train_classifier_model
AIRFLOW_CTX_EXECUTION_DATE=2025-06-11T15:27:00.244031+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-06-11T15:27:00.244031+00:00
[2025-06-11T17:37:25.379+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-11T17:37:25.379+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\nspark-submit --master local[4]   /home/monica.fernandez/practica_creativa//resources/train_spark_mllib_model.py   /home/monica.fernandez/practica_creativa/']
[2025-06-11T17:37:25.387+0200] {subprocess.py:86} INFO - Output:
[2025-06-11T17:37:27.556+0200] {subprocess.py:93} INFO - 25/06/11 17:37:27 WARN Utils: Your hostname, l090 resolves to a loopback address: 127.0.1.1; using 138.4.31.90 instead (on interface enp3s0)
[2025-06-11T17:37:27.561+0200] {subprocess.py:93} INFO - 25/06/11 17:37:27 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2025-06-11T17:37:28.819+0200] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-06-11T17:37:28.819+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/resources/train_spark_mllib_model.py", line 6, in <module>
[2025-06-11T17:37:28.821+0200] {subprocess.py:93} INFO -     import mlflow
[2025-06-11T17:37:28.821+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/mlflow/__init__.py", line 44, in <module>
[2025-06-11T17:37:28.822+0200] {subprocess.py:93} INFO -     from mlflow import (
[2025-06-11T17:37:28.822+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/mlflow/artifacts/__init__.py", line 11, in <module>
[2025-06-11T17:37:28.822+0200] {subprocess.py:93} INFO -     from mlflow.entities.file_info import FileInfo
[2025-06-11T17:37:28.823+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/mlflow/entities/__init__.py", line 6, in <module>
[2025-06-11T17:37:28.824+0200] {subprocess.py:93} INFO -     from mlflow.entities.assessment import (
[2025-06-11T17:37:28.824+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/mlflow/entities/assessment.py", line 12, in <module>
[2025-06-11T17:37:28.825+0200] {subprocess.py:93} INFO -     from mlflow.entities.assessment_error import AssessmentError
[2025-06-11T17:37:28.825+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/mlflow/entities/assessment_error.py", line 6, in <module>
[2025-06-11T17:37:28.826+0200] {subprocess.py:93} INFO -     from mlflow.utils.annotations import experimental
[2025-06-11T17:37:28.826+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/mlflow/utils/__init__.py", line 10, in <module>
[2025-06-11T17:37:28.827+0200] {subprocess.py:93} INFO -     from mlflow.utils.pydantic_utils import IS_PYDANTIC_V2_OR_NEWER  # noqa: F401
[2025-06-11T17:37:28.829+0200] {subprocess.py:93} INFO -     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-06-11T17:37:28.831+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/mlflow/utils/pydantic_utils.py", line 3, in <module>
[2025-06-11T17:37:28.833+0200] {subprocess.py:93} INFO -     import pydantic
[2025-06-11T17:37:28.833+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/pydantic/__init__.py", line 5, in <module>
[2025-06-11T17:37:28.836+0200] {subprocess.py:93} INFO -     from ._migration import getattr_migration
[2025-06-11T17:37:28.837+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/pydantic/_migration.py", line 4, in <module>
[2025-06-11T17:37:28.837+0200] {subprocess.py:93} INFO -     from .version import version_short
[2025-06-11T17:37:28.837+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/pydantic/version.py", line 5, in <module>
[2025-06-11T17:37:28.837+0200] {subprocess.py:93} INFO -     from pydantic_core import __version__ as __pydantic_core_version__
[2025-06-11T17:37:28.837+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/pydantic_core/__init__.py", line 30, in <module>
[2025-06-11T17:37:28.840+0200] {subprocess.py:93} INFO -     from .core_schema import CoreConfig, CoreSchema, CoreSchemaType, ErrorType
[2025-06-11T17:37:28.840+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/pydantic_core/core_schema.py", line 16, in <module>
[2025-06-11T17:37:28.841+0200] {subprocess.py:93} INFO -     from typing_extensions import deprecated
[2025-06-11T17:37:28.841+0200] {subprocess.py:93} INFO - ImportError: cannot import name 'deprecated' from 'typing_extensions' (/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/typing_extensions.py)
[2025-06-11T17:37:28.924+0200] {subprocess.py:93} INFO - 25/06/11 17:37:28 INFO ShutdownHookManager: Shutdown hook called
[2025-06-11T17:37:28.926+0200] {subprocess.py:93} INFO - 25/06/11 17:37:28 INFO ShutdownHookManager: Deleting directory /tmp/spark-b42e8f37-875b-4b86-90b1-799b8a03978a
[2025-06-11T17:37:29.011+0200] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-11T17:37:29.043+0200] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-11T17:37:29.066+0200] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=agile_data_science_batch_prediction_model_training, task_id=pyspark_train_classifier_model, execution_date=20250611T152700, start_date=20250611T153725, end_date=20250611T153729
[2025-06-11T17:37:29.107+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 7 for task pyspark_train_classifier_model (Bash command failed. The command returned a non-zero exit code 1.; 171874)
[2025-06-11T17:37:29.115+0200] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-06-11T17:37:29.138+0200] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
