[2025-07-10T00:53:05.885+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-07-09T22:53:00.540055+00:00 [queued]>
[2025-07-10T00:53:05.903+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-07-09T22:53:00.540055+00:00 [queued]>
[2025-07-10T00:53:05.903+0200] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-07-10T00:53:05.903+0200] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2025-07-10T00:53:05.903+0200] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-07-10T00:53:05.923+0200] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): pyspark_train_classifier_model> on 2025-07-09 22:53:00.540055+00:00
[2025-07-10T00:53:05.925+0200] {standard_task_runner.py:55} INFO - Started process 268013 to run task
[2025-07-10T00:53:05.928+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'agile_data_science_batch_prediction_model_training', 'pyspark_train_classifier_model', 'manual__2025-07-09T22:53:00.540055+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmp5rxm7m35']
[2025-07-10T00:53:05.930+0200] {standard_task_runner.py:83} INFO - Job 110: Subtask pyspark_train_classifier_model
[2025-07-10T00:53:06.009+0200] {task_command.py:388} INFO - Running <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-07-09T22:53:00.540055+00:00 [running]> on host l020.lab.dit.upm.es
[2025-07-10T00:53:06.085+0200] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=agile_data_science_batch_prediction_model_training
AIRFLOW_CTX_TASK_ID=pyspark_train_classifier_model
AIRFLOW_CTX_EXECUTION_DATE=2025-07-09T22:53:00.540055+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-07-09T22:53:00.540055+00:00
[2025-07-10T00:53:06.086+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-10T00:53:06.087+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\nspark-submit --master local[4]   /app/resources/train_spark_mllib_model.py   /app']
[2025-07-10T00:53:06.095+0200] {subprocess.py:86} INFO - Output:
[2025-07-10T00:53:07.489+0200] {subprocess.py:93} INFO - 25/07/10 00:53:07 WARN Utils: Your hostname, l020 resolves to a loopback address: 127.0.1.1; using 138.4.31.20 instead (on interface enp1s0)
[2025-07-10T00:53:07.492+0200] {subprocess.py:93} INFO - 25/07/10 00:53:07 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2025-07-10T00:53:07.876+0200] {subprocess.py:93} INFO - python3: can't open file '/app/resources/train_spark_mllib_model.py': [Errno 2] No such file or directory
[2025-07-10T00:53:07.884+0200] {subprocess.py:93} INFO - 25/07/10 00:53:07 INFO ShutdownHookManager: Shutdown hook called
[2025-07-10T00:53:07.885+0200] {subprocess.py:93} INFO - 25/07/10 00:53:07 INFO ShutdownHookManager: Deleting directory /tmp/spark-d315c12e-b3d2-47b1-83e0-b5f9ab1ba966
[2025-07-10T00:53:07.963+0200] {subprocess.py:97} INFO - Command exited with return code 2
[2025-07-10T00:53:07.976+0200] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-07-10T00:53:07.980+0200] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=agile_data_science_batch_prediction_model_training, task_id=pyspark_train_classifier_model, execution_date=20250709T225300, start_date=20250709T225305, end_date=20250709T225307
[2025-07-10T00:53:07.999+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 110 for task pyspark_train_classifier_model (Bash command failed. The command returned a non-zero exit code 2.; 268013)
[2025-07-10T00:53:08.025+0200] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-07-10T00:53:08.052+0200] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
