[2025-06-11T17:40:35.523+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-11T15:35:20.880989+00:00 [queued]>
[2025-06-11T17:40:35.557+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-11T15:35:20.880989+00:00 [queued]>
[2025-06-11T17:40:35.557+0200] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-06-11T17:40:35.557+0200] {taskinstance.py:1280} INFO - Starting attempt 2 of 4
[2025-06-11T17:40:35.557+0200] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-06-11T17:40:35.593+0200] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): pyspark_train_classifier_model> on 2025-06-11 15:35:20.880989+00:00
[2025-06-11T17:40:35.607+0200] {standard_task_runner.py:55} INFO - Started process 173637 to run task
[2025-06-11T17:40:35.613+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'agile_data_science_batch_prediction_model_training', 'pyspark_train_classifier_model', 'manual__2025-06-11T15:35:20.880989+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmp20iqo_1h']
[2025-06-11T17:40:35.614+0200] {standard_task_runner.py:83} INFO - Job 10: Subtask pyspark_train_classifier_model
[2025-06-11T17:40:35.730+0200] {task_command.py:388} INFO - Running <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-11T15:35:20.880989+00:00 [running]> on host l090.lab.dit.upm.es
[2025-06-11T17:40:35.909+0200] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=agile_data_science_batch_prediction_model_training
AIRFLOW_CTX_TASK_ID=pyspark_train_classifier_model
AIRFLOW_CTX_EXECUTION_DATE=2025-06-11T15:35:20.880989+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-06-11T15:35:20.880989+00:00
[2025-06-11T17:40:35.918+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-11T17:40:35.919+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\nspark-submit --master local[4]   /home/monica.fernandez/practica_creativa//resources/train_spark_mllib_model.py   /home/monica.fernandez/practica_creativa/']
[2025-06-11T17:40:35.954+0200] {subprocess.py:86} INFO - Output:
[2025-06-11T17:40:39.923+0200] {subprocess.py:93} INFO - 25/06/11 17:40:39 WARN Utils: Your hostname, l090 resolves to a loopback address: 127.0.1.1; using 138.4.31.90 instead (on interface enp3s0)
[2025-06-11T17:40:39.928+0200] {subprocess.py:93} INFO - 25/06/11 17:40:39 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2025-06-11T17:40:41.364+0200] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-06-11T17:40:41.364+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/resources/train_spark_mllib_model.py", line 6, in <module>
[2025-06-11T17:40:41.364+0200] {subprocess.py:93} INFO -     import mlflow
[2025-06-11T17:40:41.364+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/mlflow/__init__.py", line 44, in <module>
[2025-06-11T17:40:41.365+0200] {subprocess.py:93} INFO -     from mlflow import (
[2025-06-11T17:40:41.365+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/mlflow/artifacts/__init__.py", line 11, in <module>
[2025-06-11T17:40:41.369+0200] {subprocess.py:93} INFO -     from mlflow.entities.file_info import FileInfo
[2025-06-11T17:40:41.369+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/mlflow/entities/__init__.py", line 6, in <module>
[2025-06-11T17:40:41.371+0200] {subprocess.py:93} INFO -     from mlflow.entities.assessment import (
[2025-06-11T17:40:41.371+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/mlflow/entities/assessment.py", line 12, in <module>
[2025-06-11T17:40:41.374+0200] {subprocess.py:93} INFO -     from mlflow.entities.assessment_error import AssessmentError
[2025-06-11T17:40:41.375+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/mlflow/entities/assessment_error.py", line 6, in <module>
[2025-06-11T17:40:41.376+0200] {subprocess.py:93} INFO -     from mlflow.utils.annotations import experimental
[2025-06-11T17:40:41.376+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/mlflow/utils/__init__.py", line 10, in <module>
[2025-06-11T17:40:41.377+0200] {subprocess.py:93} INFO -     from mlflow.utils.pydantic_utils import IS_PYDANTIC_V2_OR_NEWER  # noqa: F401
[2025-06-11T17:40:41.378+0200] {subprocess.py:93} INFO -     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-06-11T17:40:41.378+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/mlflow/utils/pydantic_utils.py", line 3, in <module>
[2025-06-11T17:40:41.380+0200] {subprocess.py:93} INFO -     import pydantic
[2025-06-11T17:40:41.380+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/pydantic/__init__.py", line 5, in <module>
[2025-06-11T17:40:41.380+0200] {subprocess.py:93} INFO -     from ._migration import getattr_migration
[2025-06-11T17:40:41.381+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/pydantic/_migration.py", line 4, in <module>
[2025-06-11T17:40:41.381+0200] {subprocess.py:93} INFO -     from .version import version_short
[2025-06-11T17:40:41.381+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/pydantic/version.py", line 5, in <module>
[2025-06-11T17:40:41.386+0200] {subprocess.py:93} INFO -     from pydantic_core import __version__ as __pydantic_core_version__
[2025-06-11T17:40:41.386+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/pydantic_core/__init__.py", line 30, in <module>
[2025-06-11T17:40:41.387+0200] {subprocess.py:93} INFO -     from .core_schema import CoreConfig, CoreSchema, CoreSchemaType, ErrorType
[2025-06-11T17:40:41.388+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/pydantic_core/core_schema.py", line 16, in <module>
[2025-06-11T17:40:41.389+0200] {subprocess.py:93} INFO -     from typing_extensions import deprecated
[2025-06-11T17:40:41.389+0200] {subprocess.py:93} INFO - ImportError: cannot import name 'deprecated' from 'typing_extensions' (/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/typing_extensions.py)
[2025-06-11T17:40:41.480+0200] {subprocess.py:93} INFO - 25/06/11 17:40:41 INFO ShutdownHookManager: Shutdown hook called
[2025-06-11T17:40:41.481+0200] {subprocess.py:93} INFO - 25/06/11 17:40:41 INFO ShutdownHookManager: Deleting directory /tmp/spark-a94d27ec-38f3-4266-b050-c88f07fb931a
[2025-06-11T17:40:41.608+0200] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-11T17:40:41.632+0200] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-11T17:40:41.644+0200] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=agile_data_science_batch_prediction_model_training, task_id=pyspark_train_classifier_model, execution_date=20250611T153520, start_date=20250611T154035, end_date=20250611T154041
[2025-06-11T17:40:41.677+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 10 for task pyspark_train_classifier_model (Bash command failed. The command returned a non-zero exit code 1.; 173637)
[2025-06-11T17:40:41.691+0200] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-06-11T17:40:41.724+0200] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
